### ISSUE TITLE
HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "<host_name>": No address associated with hostname

### ISSUE THREAD

**Issue by nikunjgundaniya** [ncornette/OkCacheControl#1]
I have used your class to provide offline support to network calls. But got this error. I am using Control class this way. It's works well when online though!

```
private static OkHttpClient provideOkHttpClient() {

    return OkCacheControl.on(new OkHttpClient.Builder())
            .overrideServerCachePolicy(30, TimeUnit.MINUTES)
            .apply() // return to the OkHttpClient.Builder instance
            .build();

}
```

**Comment by ncornette** [comment]
You didn't initialize the cache by calling cache() after apply, see the readme, of okhttp documentation, it is required when using overrideServerCachePolicy, you also need to call forceCacheWhenOffline() if you want to avoid using the network when offline

**Comment by nikunjgundaniya** [comment]
Thanks for the reply. I have added the cache like this.

```
private static Cache provideCache() {
    Cache cache = null;
    try {
        cache = new Cache(new File(AdeptAndroid.getInstance().getCacheDir(), "http-cache"),
                10 * 1024 * 1024); // 10 MB
    } catch (Exception e) {
        Log.d("Test", "Could not create Cache!");
    }
    return cache;
}
```

Changed OkHttpControl initialization

```
private static OkHttpClient provideOkHttpClient() {

    return OkCacheControl.on(new OkHttpClient.Builder())
            .overrideServerCachePolicy(30, TimeUnit.MINUTES)
            .apply() // return to the OkHttpClient.Builder instance
            .cache(provideCache())
            .build();
}
```

For forceCacheWhenOffline() it's requires the NetworkMonitor. Can you please tell me how can I get one?

**Comment by ncornette** [comment]
```
            new OkCacheControl.NetworkMonitor() {
                @Override
                public boolean isOnline() {
                    ConnectivityManager connectivityManager = (ConnectivityManager) getApplicationContext().getSystemService(Context.CONNECTIVITY_SERVICE);
                    NetworkInfo activeNetworkInfo = connectivityManager.getActiveNetworkInfo();
                    return activeNetworkInfo!=null && activeNetworkInfo.isConnected();
                }
            }
```

**Comment by nikunjgundaniya** [comment]
Okay thanks those previous errors were gone but there are new ones. It's down below. I have got this log from HttpLoggingInterceptor.

D/Log: Content-Type: application/x-www-form-urlencoded
D/Log: Content-Length: 122
D/Log: --> END POST
D/Log: <-- 504 Unsatisfiable Request (only-if-cached) <a link>
D/Log: Cache-Control: max-age=1800
D/Log: <-- END HTTP

**Comment by ncornette** [comment]
This error means you asked for cache only response (because you are offline), but the response isn't available in cache, you need to handle this error yourself

**Comment by nikunjgundaniya** [comment]
Okay sure I will do that. Just one last question though. So this means OkCacheControl won't cache my response. I have to do it by myself? Is it you are suggesting? Because I have got the response when I am online. I thought OkCacheControl will store in the app cache and retrieve it from cache when device is in offline state.

**Comment by ncornette** [comment]
The 504 response is automatic response from OKHTTP when request header `only-if-cached` is provided and there is no response in cache, this is what happens when `NetworkMonitor#isOnline` returns false, so are you sure you were online? 

Second point : Because the cache is a cache, responses may have been evicted for some reason, so you need to take into account that the response is missing by handling the 504 error.

Third point :  Not all responses are good candidates for cache, you should consider using `Cache-Control: no-cache` or `Cache-Control: no-store` for those requests. (refer to [README](https://github.com/ncornette/OkCacheControl/blob/master/README.md) for implications)

Hope it will help!

**Comment by ncornette** [comment]
Note: implementation of `OkCacheControl.NetworkMonitor` I provided in my comment may not be the best for all cases :-) you are free to find a better one.

**Comment by nikunjgundaniya** [comment]
Thanks mate! Got your point!
